### ISSUE TITLE
Error registering the participants

### ISSUE THREAD

**Issue by Giton22** [Drarig29/brackets-storage#11]
Hi! I'm using the lib with prisma client but all the time it want's to insert participants it's failing, but I don't know why.

Using Prisma@4.16.2
```
e9a78b22-b506-4ce9-a00d-02f28b74d846 SELECT "participant" args: [{"tournament_id":5}]
e9a78b22-b506-4ce9-a00d-02f28b74d846 469ms - Returned []
070c482e-8b9c-4d82-b2ec-e0a4c81450fc INSERT "participant" args: [[{"tournament_id":5,"name":"Team 1"},{"tournament_id":5,"name":"Team 2"},{"tournament_id":5,"name":"Team 3"},{"tournament_id":5,"name":"Team 4"}]]
070c482e-8b9c-4d82-b2ec-e0a4c81450fc 148ms - Returned false

 ERROR  [nuxt] [request error] [unhandled] [500] Error registering the participants.
```

The code:
```
  await manager.create.stage({
    tournamentId: 5,
    name: 'Elimination stage',
    type: 'double_elimination',
    seeding: ['Team 1', 'Team 2', 'Team 3', 'Team 4'],
    settings: { grandFinal: 'double' },
  });
```

**Comment by Drarig29** [comment]
Did you set up prisma and your database?

**Comment by Giton22** [comment]
Yeah sure I added schema.prisma, did npx prisma@4.16.2 generate and npx prisma@4.16.2 db push
here's the supabase website: 
![image](https://github.com/Drarig29/brackets-storage/assets/24484823/a348068a-c486-4f1a-b0ae-efc79f4905f6)

**Comment by Giton22** [comment]
Hmm strange... I didn't change anything since yesterday but now it's creating the stage+participants.. But getting tournamentData is still giving empty object with props. 

```
e71af643-8342-4bb8-a9bd-dcc6df0d31b2 SELECT "stage" args: [{"tournament_id":0}]
e71af643-8342-4bb8-a9bd-dcc6df0d31b2 308ms - Returned []
004afab7-f83a-4331-bdf5-75cb679a5919 SELECT "participant" args: [{"tournament_id":0}]
004afab7-f83a-4331-bdf5-75cb679a5919 47ms - Returned []
```

![image](https://github.com/Drarig29/brackets-storage/assets/24484823/032d0013-15a8-4962-baa4-0a2b0fe515b0)
![image](https://github.com/Drarig29/brackets-storage/assets/24484823/63fbda41-acca-4da4-bbc8-c31186f49f57)

**Comment by Giton22** [comment]
Okay found out, it was a Postgres issue, supabase use pgbouncer and I forgot to add ?pgbouncer=true at the end of the connection string, so now it work fine. Sorry for disturbing!
