### ISSUE TITLE
missing class properties transform error in brackets-memory-db

### ISSUE THREAD

**Issue by dixitt5** [Drarig29/brackets-storage#2]
Hey,
I'm getting this error : Missing class properties transform.
   5 | const clone = rfdc();
   6 | class InMemoryDatabase {
>  7 |     data = {
     |     ^
   8 |         participant: [],
   9 |         stage: [],
  10 |         group: [],

while trying to use it in React.
Can you provide any example template code for using it in react. also maybe you can provide any direct contact so I can ask issues to you directly ( I know it's much but maybe you can provide) . I really need this for my hackathon project :)

**Comment by Drarig29** [comment]
Did you look at StackOverflow questions like [this one](https://stackoverflow.com/questions/35517245/error-missing-class-properties-transform) or search in Google?

This seems related to babel, when doing transpilation.

**Comment by dixitt5** [comment]
I've tried every solutions given in stackoverflow and google. But nothing seems to be working with the code. I've used various iterations of Babel config too, to see if one runs correctly.

**Comment by Drarig29** [comment]
Do you use TypeScript in React?

**Comment by Drarig29** [comment]
Can you create a public repository on GitHub which reproduces the issue?

**Comment by dixitt5** [comment]
I'm using JavaScript in React .
yeah sure, let me create one.

**Comment by dixitt5** [comment]
here you go, created the repo.
https://github.com/dixitt5/bracket-generator

**Comment by Drarig29** [comment]
@dixitt5 you just had to upgrade `react-scripts` apparently 😄 

The dev dependency `@babel/plugin-proposal-private-property-in-object` is required to remove some warnings.

Also, there are some error logs about source maps, but I think it's just because I don't publish then in my NPM packages. It's safe to ignore and it compiles though.
