### ISSUE TITLE
Final Standings in wrong order in `prisma-db`

### ISSUE THREAD

**Issue by Tandashi** [Drarig29/brackets-storage#6]
The final standings are all mixed up and not correct when using `prisma-db`.
This has to do with the fact that the `brackets-manager` requires things to be ordered by:

1. `number`
2. nested `number` (e.g. for the `round`)

**Comment by Drarig29** [comment]
Hey! 

Again, I saw your PR but I cannot release it. For now, I don't have a computer to use the `npm` CLI.

**Comment by Tandashi** [comment]
All good no worries. Was just for when you are back home, whenever. Already patched the version locally.
